kind: Route
apiVersion: route.openshift.io/v1
metadata:
# set your user name
  name:  {{ .Values.containers.containerPort }}
spec:
  to:
    kind: Service
# set your user name
    name:  {{ .Values.containers.containerPort }}
    weight: 100
  port:
    targetPort: {{ .Values.service.servicePort }}
  wildcardPolicy: None