kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: blue-green-route
  annotations:
    haproxy.router.openshift.io/balance: random
spec:
  to:
    kind: Service
    name: user13-hello-chart-service
    weight: 0
  alternateBackends:
  - kind: Service
    name: user13-hello-izzy
    weight: 100